
import type { Metadata } from "next";
import "./globals.css";
//import BottomNav from "@/components/BottomNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
  <div style={{ paddingBottom: "70px" }}>
    {children}
  </div>

  {/* 👇 ADD THIS */}
 
</body>
    </html>
  );
}
/*function NavButton({ label }: { label: string }) {
  return (
    <button
      style={{
        background: "transparent",
        border: "none",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "4px",
        fontSize: "12px",
        color: "#555",
        padding: "8px 12px",
        borderRadius: "12px",
        transition: "all 0.2s ease",
        cursor: "pointer",
      }}
      onMouseDown={(e) => {
        e.currentTarget.style.transform = "scale(0.92)";
      }}
      onMouseUp={(e) => {
        e.currentTarget.style.transform = "scale(1)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = "scale(1)";
      }}
    >
      <div
        style={{
          width: "6px",
          height: "6px",
          background: "#2563eb",
          borderRadius: "50%",
        }}
      />
      {label}
    </button>
  );
}*/
